### ISSUE TITLE
TemperatureDifference: conversion factor between Fahrenheit and Kelvin is incorrect

### ISSUE THREAD

**Issue by joseph-bs** [objorke/QuantityTypes#13]
In Units.csv, the conversion factor between DegreeFahrenheit and DegreeKelvin should be 5.0/9 rather than 9.0/5 because:

> A temperature interval of 1 °F is equal to an interval of 5⁄9 degrees Celsius. ([Wikipedia](https://en.wikipedia.org/wiki/Fahrenheit))

 ```Diff
 TemperatureDifference,DegreeKelvin,K,1
 TemperatureDifference,DegreeCelsius,C,1
-TemperatureDifference,DegreeFahrenheit,F,9.0 / 5
+TemperatureDifference,DegreeFahrenheit,F,5.0 / 9.0
 
 LinearMomentum,KilogramMeterPerSecond,kg*m/s,1
 LinearMomentum,NewtonSecond,N*s,1
```

**Comment by objorke** [comment]
Thanks for the bug report. A pull request including a unit test is wanted! :-)

**Comment by joseph-bs** [comment]
Will do, early next week.

**Comment by joseph-bs** [comment]
Pull request #19
