### ISSUE TITLE
Cannot use symbols for units due to bug in Utilities

### ISSUE THREAD

**Issue by baylesj** [objorke/QuantityTypes#20]
Even if I register the the unit using
```c#
UnitProvider.Default.RegisterUnit(Length.Foot, "'");
```
Due to this compare in Utilities.cs TrySplit function on line 51
```c#
if (char.IsLetter(c) || c == '%' || c == '°')       
```
I cannot use special symbols to handle common types. In the US, ' and " are common symbols for feet and inches but do not work in QuantityTypes.

It looks like a fix could be had by changing the compare to be 
```c#
if (!char.IsNumber(c) && c != "." && c != ",") {}
```

Although I am not sure.

I'll fix it and push up a pull request if I get time.

**Comment by objorke** [comment]
It is important that strings like "1e+2 m" and "1E-2 m" can be parsed. Please add unit tests for these cases if they are not already covered.
Also add a unit test using the exa prefix, e.g. "1Em" or "1 Em". 
Do you know any units starting with lowercase "e"?

**Comment by jotschgl** [comment]
I only know eV: https://en.wikipedia.org/wiki/Electronvolt
