### ISSUE TITLE
unit prefixes should be case sensitive

### ISSUE THREAD

**Issue by donid** [objorke/QuantityTypes#23]
It is impossible to add common unit prefixes like:
ElectricResistance,Milliohm,mΩ,1e-3
ElectricResistance,Megaohm,MΩ,1e6//does not work:unit is case insensitive
because QuantityTypes.UnitProvider will throw an exception.

(see: https://en.wikipedia.org/wiki/Unit_prefix)

**Comment by donid** [comment]
Hi, since you have tagged this issue "help wanted" I have examined the source code, to
find out what changes would be necessary to resolve this issue. It turns out that only
"StringComparer.OrdinalIgnoreCase" has to be removed from a Dictionary constructor-call and
two unit test have to be slightly modified. This confuses me a bit, because the Dictionary
is case-sensitive by default, so this was intentionally changed to case-insensitive.

So, are you fine with this change - that would be a "major"/breaking change because it
breaks existing behavior and the version number should reflect this, if you would
accept a pull request for this...

**Comment by objorke** [comment]
I don´t remember any reason for making it case-insensitive, this is probably a bug. Yes, I will accept a PR  fixing this. Please make a good commit description! :-)
