### ISSUE TITLE
TemperatureChange quantity should be renamed

### ISSUE THREAD

**Issue by joseph-bs** [objorke/QuantityTypes#42]
The `TemperatureChange` quantity actually refers to a temperature _rate of change_ (the ratio of a temperature difference and a time duration). I think that the current name is misleading and can be easily confused with `TemperatureDifference`.

`TemperatureRateOfChange` would be more accurate and is the common way of referring to it - a Google search on "temperature rate of change" finds 309 million results.

The only drawback is that the name is long. But if anything should be dropped, it's "change" rather than "rate". From [Wikipedia article on Rate](https://en.wikipedia.org/wiki/Rate_(mathematics)):

> In mathematics, a rate is the ratio between two related quantities. Often it is a rate of change. If the unit or quantity in respect of which something is changing is not specified, usually the rate is per unit of time. However, a rate of change can be specified per unit of time, or per unit of length or mass or another quantity. The most common type of rate is "per unit of time", such as speed, heart rate and flux. Ratios that have a non-time denominator include exchange rates, literacy rates and electric field (in volts/meter).

"Rate of change" is often abbreviated as "ROC" but `TemperatureRoc` wouldn't be self-explanatory for most people.

So would you be fine with `TemperatureRateOfChange`?

What do you suggest?

**Comment by objorke** [comment]
TemeratureRateOfChange sounds good!
