### ISSUE TITLE
Add Count quantity type

### ISSUE THREAD

**Issue by czuvich** [objorke/QuantityTypes#47]
Is Fraction the standard unit for "count"?  
See https://developer.apple.com/library/ios/documentation/HealthKit/Reference/HKUnit_Class/#//apple_ref/occ/clm/HKUnit/unitFromString:

**Comment by objorke** [comment]
Should a count quantity be an integer?
https://developer.apple.com/library/ios/documentation/HealthKit/Reference/HKUnit_Class/#//apple_ref/occ/clm/HKUnit/countUnit

The `Fraction` quantity type is like the percent unit.
https://developer.apple.com/library/ios/documentation/HealthKit/Reference/HKUnit_Class/#//apple_ref/occ/clm/HKUnit/percentUnit

**Comment by objorke** [comment]
Closing this issue due to no response. I think `int` is a good type for countable quantities! You could use a validation attribute to ensure it is >=0.
