### ISSUE TITLE
sign assembly in nuget package

### ISSUE THREAD

**Issue by naspert** [objorke/QuantityTypes#51]
it would be nice if the assembly in the nuget package had a strong name

**Comment by objorke** [comment]
Should we check-in a private key?
Or can we use [public signing](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/public-signing.md)?
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

**Comment by objorke** [comment]
I see JSON.NET is signed with a key that is not checked in:
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Build/build.ps1#L201

**Comment by objorke** [comment]
I have simply checked in the generated key as suggested on the dotnet/corefx page. Let us know if this is not a good idea.

**Comment by naspert** [comment]
I would advise against including the signing key in the source tree. You should only use it when you generate the nuget packages and keep it private to you/the build server.

**Comment by objorke** [comment]
Did you see that Microsoft wrote:
_Firstly, we would recommend that these open source projects check-in their private key (remember, strong-names are used for identity, and not for security)._

**Comment by naspert** [comment]
Yeah, they also advised me to upgrade to windows 10 ;) That was just my $0.02 anyway, I guess there is no real risk of having your identity in the wild.
