### ISSUE TITLE
Support serialisation of Quantity Type

### ISSUE THREAD

**Issue by jotschgl** [objorke/QuantityTypes#53]
I saw the use of the Serializable Tag in the Quantity classes. But it is used only when the PCL compilation symbol is not set. So i tried to remove it and build the library on my own, but then it does not build.

**Comment by objorke** [comment]
I don't think SerializableAttribute is available in the chosen PCL profile. Which serializer do you want to use? Xml and JSON serializers should work fine.

**Comment by jotschgl** [comment]
Im am very sorry. Just tried it again and it is working like a charm. I don't know what I did wrong the last time. This issue can be closed and/or removed,

**Comment by jotschgl** [comment]
Just realised the difference between my first attempt which failed and the working one. 
If I use Quantities in a .NET remoting application, using the standard remoting serializer, it is not working because the [Serializable] Attribute is missing

**Comment by objorke** [comment]
Can you use the NET40 assembly?
Or do we need to build a NET45 version, too.
SerializableAttribute should be included in non-PCL builds:
https://github.com/objorke/QuantityTypes/blob/master/Source/QuantityTypes/Quantities/Area.cs#L31
