### ISSUE TITLE
Microgram unit abbreviation includes an incorrect blank abbreviation

### ISSUE THREAD

**Issue by ShawnWeaver** [objorke/QuantityTypes#55]
The Units.csv uses "ug||µg" to define its two abbreviations, which causes the generator to create a blank ("") abbreviation for it. It looks like this should be "ug|µg".

I've created a simple pull request to fix it ( #54 ), but I haven't had a chance to regenerate any of the unit code.

It might be prudent to update the generator to ignore empty abbreviations (and maybe also leading/trailing spaces?), but I can't create a one-character pull request for that...

**Comment by objorke** [comment]
done
