### ISSUE TITLE
Add more torque units

### ISSUE THREAD

**Issue by objorke** [objorke/QuantityTypes#8]
Add 

- [x] `J/rad` 
- [x] `N*mm`
- [x] `N*cm`

and units based on mass at surface of the earth:

- [x] `lb*ft` (pounds-force-feet) or `ft*lb` (foot-pound force)
- [x] `ft*pdl` (foot-poundal)
- [x] `in*lbf` (inch-pound force)
- [x] `oz*in` (ounce-force-inches) or `in*ozf`?
- [x] `g*cm` (gram-centimetre) or `cm*g`?
- [x] `tonne*m` (tonne-metre) or `m*tonne`?

where
gravity = 9.80665 m/s^2

http://en.wikipedia.org/wiki/Conversion_of_units#Torque_or_moment_of_force
http://www.convertunits.com/info/tonne-meter
http://en.wikipedia.org/wiki/Torque

**Comment by mrichwin** [comment]
I'd also appreciate N*mm and N*cm, being practical units for me.

**Comment by objorke** [comment]
Simply add the units to `Units.csv`
https://github.com/objorke/QuantityTypes/blob/master/Source/QuantityTypes/Quantities/Units.csv#L152

and make a pull request!

**Comment by mrichwin** [comment]
Done (for N*cm, N*mm, not sure about the others suggested on top)
