### ISSUE TITLE
QuantityJsonConverter

### ISSUE THREAD

**Issue by slimjack** [objorke/QuantityTypes#85]
In `QuantityJsonConverter` `NullReferenceExcpetion` may occur. There should be a `return` after `serializer.Serialize(writer, null);`.

Very helpful library! Thank you.

**Comment by objorke** [comment]
https://github.com/objorke/QuantityTypes/blob/master/Source/QuantityTypes.Tests/JsonTests/QuantityJsonConverter.cs#L31
