### ISSUE TITLE
Upgrade to '.NETStandard,Version=v1.3'.

### ISSUE THREAD

**Issue by SamLebarbare** [objorke/QuantityTypes#87]
It is possible to have a nuget release for .NETStandard 1.3?

**Comment by objorke** [comment]
we could try!
Do you need to consume the library from a .netstandard 1.3 / .net 4.6 project?

where do we need to change:
https://github.com/objorke/QuantityTypes/blob/master/Source/QuantityTypes/project.json#L11
https://github.com/objorke/QuantityTypes/blob/master/Source/QuantityTypes/QuantityTypes.xproj#L13

I am confused about the project.json/xproj stuff - waiting for the final solution around this...

**Comment by SamLebarbare** [comment]
> Do you need to consume the library from a .netstandard 1.3 / .net 4.6 project?

Yes thx!

**Comment by SamLebarbare** [comment]
With:

```
"frameworks": {
    "netstandard1.0": {
      "dependencies": {
        "NETStandard.Library": "1.6.0",
        "System.Xml.XmlSerializer": "4.0.11"
      }
    },
    "netstandard1.3": {
      "dependencies": {
        "NETStandard.Library": "1.6.0",
        "System.Xml.XmlSerializer": "4.0.11"
      }
    }
  },
```

You must have the additional target, no?

**Comment by objorke** [comment]
Isn't this already supported? We target `netstandard1.0`.
I tested v3.0.1 with various versions of .NET core and .NET framework and did not see any problems.
