### ISSUE TITLE
Add Scandinavian Mile

### ISSUE THREAD

**Issue by jussidynabyte** [objorke/QuantityTypes#88]
It would be good to add the Scandinavian Mile (10 km) as that unit is used a lot in Scandinavia. 

https://en.wikipedia.org/wiki/Scandinavian_mile

**Comment by objorke** [comment]
I think this could be added here:
https://github.com/objorke/QuantityTypes/blob/master/Source/QuantityTypes/Units.csv#L17

`Length,ScandinavianMile,mil,1e4`
